import { Injectable } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';

// Node.js built-in crypto functions.
// createCipheriv  -> used for encryption.
// createDecipheriv -> used for decryption.
// randomBytes -> generates cryptographically secure random bytes.
import {
  createCipheriv,
  createDecipheriv,
  randomBytes,
} from 'crypto';


@Injectable()
export class EncryptionService {

  // The encryption algorithm we are going to use.
  //
  // AES       -> symmetric encryption algorithm.
  // 256       -> uses a 256-bit key (32 bytes).
  // GCM       -> provides encryption + integrity/authentication.
  private readonly algorithm = 'aes-256-gcm';

  // Stores our encryption key as a Buffer.
  //
  // We use Buffer because Node's crypto API works with binary data.
  private readonly key: Buffer;


  constructor(private readonly configService: ConfigService) {

    // Read ENCRYPTION_KEY from the application's configuration.
    //
    // <string> tells TypeScript that we expect this value to be a string.
    const key = this.configService.get<string>('ENCRYPTION_KEY');

    // If the encryption key doesn't exist,
    // stop the application instead of running with an invalid configuration.
    if (!key) {
      throw new Error('ENCRYPTION_KEY is not configured');
    }

    // Convert the key from a hexadecimal string into actual bytes.
    //
    // Example:
    // "a1b2c3..." (hex string)
    //        ↓
    // Buffer containing the actual bytes.
    this.key = Buffer.from(key, 'hex');

    // AES-256 requires exactly 256 bits = 32 bytes.
    //
    // If the key has another size, the encryption algorithm
    // will not work correctly.
    if (this.key.length !== 32) {
      throw new Error('ENCRYPTION_KEY must be 32 bytes');
    }
  }

  // Encrypts a plaintext string and returns the encrypted value as a string.
  encrypt(text: string): string {

    // Generate a new random Initialization Vector (IV).
    //
    // GCM normally uses a 12-byte IV.
    //
    // IMPORTANT:
    // We generate a new IV for every encryption.
    const iv = randomBytes(12);

    // Create the encryption cipher.
    //
    // algorithm -> AES-256-GCM
    // key       -> our secret encryption key
    // iv        -> random IV generated above
    const cipher = createCipheriv(
      this.algorithm,
      this.key,
      iv,
    );

    // Encrypt the plaintext.
    //
    // cipher.update() processes the input.
    // cipher.final() finishes the encryption process.
    //
    // Buffer.concat() combines both encrypted parts into one Buffer.
    const encrypted = Buffer.concat([
      cipher.update(text, 'utf8'),
      cipher.final(),
    ]);

    // Get the authentication tag generated by GCM.
    //
    // The auth tag allows us to detect if the encrypted data
    // has been modified or tampered with.
    const authTag = cipher.getAuthTag();

    // Return all the information needed for decryption:
    //
    // 1. IV
    // 2. Authentication Tag
    // 3. Encrypted data
    //
    // We convert each one to hexadecimal because
    // we want to store the result as a normal string in MongoDB.
    //
    // Example:
    //
    // iv:authTag:ciphertext
    return [
      iv.toString('hex'),
      authTag.toString('hex'),
      encrypted.toString('hex'),
    ].join(':');
  }

  // Decrypts an encrypted value and returns the original plaintext.
  decrypt(value: string): string {

    // Our encrypted value was stored as:
    //
    // iv:authTag:ciphertext
    //
    // So we split it back into its three components.
    const [ivHex, authTagHex, encryptedHex] = value.split(':');

    // Create the decryption cipher.
    //
    // We use the SAME:
    // - algorithm
    // - encryption key
    // - IV
    //
    // that were used during encryption.
    const decipher = createDecipheriv(
      this.algorithm,
      this.key,
      Buffer.from(ivHex, 'hex'),
    );

    // Give GCM the authentication tag.
    //
    // During decipher.final(), GCM will verify the auth tag.
    //
    // If someone modified the encrypted data,
    // authentication will fail and decryption will throw an error.
    decipher.setAuthTag(
      Buffer.from(authTagHex, 'hex'),
    );

    // Decrypt the ciphertext.
    //
    // Convert the encrypted hexadecimal string back into a Buffer.
    // Then decrypt it using update() and final().
    const decrypted = Buffer.concat([
      decipher.update(
        Buffer.from(encryptedHex, 'hex'),
      ),
      decipher.final(),
    ]);

    // The decrypted result is a Buffer.
    //
    // Convert it back into a normal UTF-8 string
    // so the caller gets the original plaintext.
    return decrypted.toString('utf8');
  }
}